### ISSUE TITLE
Runs but throws exceptions

### ISSUE THREAD

**Issue by Navyguy330** [Betalord/BHBot#10]
I am having issues running, it logs in ok, but basically while logging in it throws a few different exceptions in the console. 

I could print them out but basically normal crashing sort of stuff. 

for the most part I believe i have everything needed as I believe it wouldnt even run and especially not open and login to the game.

any help is greatly appreciated.

**Comment by cagamoo** [comment]
if it is connecting and logging in, we would need the crash report.
also paste in your settings file. **(censor your username and password)**
some settings get read after wards and cause crashes.
_check out my fork if you can compile java_

**Comment by bloodey** [comment]
@cagamoo can you provide updated executables please? Because old releases cant run gvg, invasion etc :( and i dont have permission to compile sources in this pc.

**Comment by Fortigate** [comment]
new executable added under releases.
