### ISSUE TITLE
Ad watching not working

### ISSUE THREAD

**Issue by Fortigate** [Betalord/BHBot#14]
The ad delivery system was changed last year so the existing code does not work.

**Comment by Fortigate** [comment]
Attempted to work on this for the last week or so but I am unable to get the website to serve me any ads to use for testing. Shelving this feature until I can find a way around this issue.

**Comment by Larrush** [comment]
What do you mean you can´t get the website to serve you any ads? 
Are there no ads, that you can use with the bot, or generally no ads?
