### ISSUE TITLE
Chrome v69

### ISSUE THREAD

**Issue by KiloChaser** [Betalord/BHBot#18]
I can't find a download for Chrome v69. Offline installers just install the latest version v71. Is there a download link that you know works?

**Comment by Fortigate** [comment]
I used the download from here: https://www.neowin.net/news/google-chrome-69-offline-installer-direct-download-links/

I also had to disable the Google update services to stop it from automatically updating when the browser was closed. I'll see if I can find a better solution as this isn't really long term sustainable ..

**Comment by KiloChaser** [comment]
Awesome thank you!

**Comment by KiloChaser** [comment]
Annnnd nevermind! The download links for the offline installer returns a 404 error code.

**Comment by Fortigate** [comment]
Seems Google have taken it off their site, this link should still work https://www.itechtics.com/download-google-chrome-69/

**Comment by KiloChaser** [comment]
I downloaded the installer from that site, and installed it while in airplane mode. It just installed the latest version of chrome, v71. It seems like finding older versions is much more difficult than it should be. Is there any way to use Firefox instead?

**Comment by KiloChaser** [comment]
I found a v69 of chrome, I will get back to you in a few hours when I finish my schoolwork.

**Comment by KiloChaser** [comment]
How did you stop chrome from updating? I disabled both services and deleted the update executable but it updated anyways... The bot did work for a while but as soon as chrome updated it broke. Thanks!

**Comment by Fortigate** [comment]
After a bit of digging you can download a development version of Chromium v69 from the google site here: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/576753/. and change the code in Mainthread to include;

ChromeOptions options = new ChromeOptions();
options.setBinary("/path/to/other/chrome/binary");

I know a lot of people use chrome as their main browser and keeping it on v69 and disabling updates is not really an option, so I'll look into making this the standard install method. I don't have a lot of time at the moment for development but will re-open this and place on the to do list.

**Comment by Fortigate** [comment]
New release added, now runs on Chromium rather than Chrome. Updated setup guide to reflect this.
