### ISSUE TITLE
Gauntlet Cue

### ISSUE THREAD

**Issue by vidabohemia666** [Betalord/BHBot#2]
Replace gauntlet cue with this one.

Also I think ads are not working... Will check it later
![cuegauntlet](https://user-images.githubusercontent.com/33652270/32769857-9dbf0b9a-c904-11e7-89e5-d4fdb0668fea.png)

**Comment by vidabohemia666** [comment]
By the way, thanks for the EXCELENT job!

**Comment by Keldon80** [comment]
What version of chromedriver are you using ? Mine create a new Blank Chrome Folder every some minutes...

**Comment by Keldon80** [comment]
thx for the cue btw

**Comment by Fortigate** [comment]
Updated and working with updated cue file!
