### ISSUE TITLE
Linux files missing

### ISSUE THREAD

**Issue by bubhubububhuhb** [Betalord/BHBot#21]
Where they removed for some reason? I cannot find the web folder at all. Web/linux scripts, as it is described in the wiki.

**Comment by Fortigate** [comment]
I removed them after changing the bot from from Chrome to Chromium as I didn't have time to support and test on multiple OS's/Browsers, so decided to support Windows + Chromium only (Not my main OS.. but figured it had the widest usage). 

Let me know if you want a copy of the Linux and webserver folders to see if you get them working and I'm happy to add it back.

**Comment by bubhubububhuhb** [comment]
That would be great

**Comment by Fortigate** [comment]
[BHBot_Linux.zip](https://github.com/Betalord/BHBot/files/2847321/BHBot_Linux.zip)

Let me know how you get on with it!
