### ISSUE TITLE
PVP stripping doesnt work

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#23]
When I activate stripping down the bot gets stuck at shown error
![lightshot](https://user-images.githubusercontent.com/47528224/52667871-58f6d900-2f12-11e9-99ca-4af02e77d3d6.jpg)

**Comment by Fortigate** [comment]
Can you try this version? Should fix it.
[BHBot.zip](https://github.com/Betalord/BHBot/files/2858032/BHBot.zip)

**Comment by Larrush** [comment]
Fixed the Issue! 
Thanks so much!
