### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#24]
This is not an Issue, but I wasn´t sure where else I could post it.
Would it be possible to implement a reviving/heal function?

Where once a group member dies, the bot resurrects them and continues the game.

There is another bot that can do that, but I prefer to use this one since its so much more convenient.
(The other bot does it by activating Disable autopilot on death. When someone dies, the game "pauses" and the bot searches for the grave.  Depending on your settings he uses either a small, average or big potion.  I thought this might help.)

Sorry for posting this in the Issue section! I am not too familiar with GitHub.

**Comment by Fortigate** [comment]
Sounds good, I'll have a look at implementing it!

**Comment by Fortigate** [comment]
added in [v31](https://github.com/Betalord/BHBot/releases/tag/v31). feedback on it would be appreciated. Until I run out of potions I don't have any way of scripting what happens in that scenario so be weary.

**Comment by Larrush** [comment]
So far it works good for me!
I just forgot to activate "disable autopilot" for the first few runs.

I will tell you how it works for me in a few days.
Got a few hundred potions^^

Big thanks again to you for making the work!
Even if you enjoyed doing it, I appreciate it!

**Comment by Larrush** [comment]
It seems when using the "hidewindowonstart" option the auto revive function doesn´t work.
I´ll have to check if that was a one time thing
