### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bbicudo** [Betalord/BHBot#27]
The console says "Game element found. Starting to run bot..." and nothing happens in the game. What do i do?

**Comment by Larrush** [comment]
Have you started the Ini.bat before the bhbot.bat?
Have you configured the settings.ini so that the bot actually knows what to do?

**Comment by Larrush** [comment]
Also it might be an issue with your screen resolution or if you use a second screen.
At least that was my problem when using it the first time.
It should be mainscreen and I think 1920x1080

**Comment by bbicudo** [comment]
Thanks bro, it was screen resolution :heart:

**Comment by hieutrpham** [comment]
![image](https://user-images.githubusercontent.com/37964079/56086016-c55f5d00-5e1b-11e9-8073-f7ebd83282fb.png)

The bot does nothing for me after checking autoshrines disabled

**Comment by hieutrpham** [comment]
![image](https://user-images.githubusercontent.com/37964079/56086198-9519bd80-5e1f-11e9-9d69-e249df04c476.png)

Hello, I can start the bot but after it checks autoshrines is disable it doesn't do anything else. I can force it to run a raid but it doesn't do anything more than that. Can you help with this issue? Thank you!
