### ISSUE TITLE
Raid 

### ISSUE THREAD

**Issue by federico-rocchegiani** [Betalord/BHBot#3]
Hi, first of all thanks for the excellent job!
Than, I have an issue with the raid, every time the bot attemp to do it, happens this error:
"Error: detected raid type is 0, which is an error. Restarting..."
and than:
"Doing driver emergency restart..."

It seems it can't detect the R1Only cue or something like this.
Thank you very much!

**Comment by The-Boogieman** [comment]
It can actually detect the cue, but it seems the script is faulty in this matter and assigns R0 to it, which is invalid. Just delete cueR1 and rename cueR1Only to cueR1. It will work perfectly.

You will probably need to restore the original cueR1 after you unlock R2 ingame.

**Comment by brewcrew02** [comment]
I get the same problem, how can we fix this!?

**Comment by Fortigate** [comment]
Issue fixed thanks to @cagamoo
