### ISSUE TITLE
Pvp stripping

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#30]
Lately he always leaves my head off after pvp, but usually doesn't give me an error message for that.

He once gave me a message like: "couldn't find equipment button" but I forgot to screenshot it.

I'll turn around the command so head is first and mainhand is second to see if it still occurs in that order

**Comment by Fortigate** [comment]
I'll have a look at the code, I experience the same thing I few times a week where it doesn't re-equip my offhand but figured that my macro force closing chrome/bhbot was killing the process during a pvp event.

I should find some time this weekend to quickly push out and update for T10 as well as long as they don't change too much!

**Comment by Larrush** [comment]
Yeah that also happened to me a few times wherr the macro just forced the exit at the wrong time^^

**Comment by Fortigate** [comment]
The new update removed the 2300 TS cap on points.. so I guess I'll depreciate this feature unless it still serves a purpose

**Comment by ilpersi** [comment]
It was not working with the new content because of the new Augments category so I fixed that anyway.

**Comment by Fortigate** [comment]
Yup it was messing with consumable use too with the extra category in the list.

Is item stripping still going to be useful with GvG? Or is the sudden death activated in that too?

**Comment by ilpersi** [comment]
I don't know but at least for a while I would keep this option. Cause the bot is running PVP and GVG unattended I'd rather have it doing it with lower levels to have a steady amount of points.

I've also reviewed the checks to identify equipped slots and created a new cue for it, it should be much more reliable.

**Comment by Fortigate** [comment]
Closing for now then as @ilpersi has fixed the original issue.
