### ISSUE TITLE
Mavenize the project

### ISSUE THREAD

**Issue by ilpersi** [Betalord/BHBot#31]
Hi,
I would like to switch the project to a [Maven](https://maven.apache.org/) one. This has the following advantages over the current status:

* Maven could automatically manage the dependencies making it easier to update/upgrade them or to add new ones should we need them
* Because of the previous point we would be able to remove dependencies from the source
* Once that the project is mavenized we can strip down the size of the jar to about 9.4 Megabytes from the current size

@Fortigate are you ok with this?

**Comment by Fortigate** [comment]
Yup fine by me. Amazingwork so far by the way!

Do you have any more features you want to add soon? If there's nothing big I'll test v33 tonight and compile/release it tomorrow.

**Comment by ilpersi** [comment]
I'll wait for release 33 and mavenize the project after it is released so all the fixes for the new contents are out.

After the "mavenization", I plan to introduce a couple of new features.

**Comment by Larrush** [comment]
Man you guys are rocking it right now!
Big thanks from me for the great work you've been putting into this :)

**Comment by ilpersi** [comment]
Project moved to Maven. Once I run the package target, the size is quite reduced. Now managing dependencies is a breeze. 😄 

[![suD6WiFYZo.png](https://i.imgur.com/iss5ld9.png)](https://i.imgur.com/iss5ld9.png)
