### ISSUE TITLE
auto shrine

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#33]
![Untitled](https://user-images.githubusercontent.com/47528224/54273316-f54de300-4585-11e9-893d-e399e594508f.jpg)

Found another issue with autoshrine.
When checking shards/tokens in the middle of another action, he activates autoshrine, but if there are no available points he sometimes forgets to deactivate.
But when he starts a dungeon after that, he gets lost since he isn´t used to having shrine active while running dungeons

**Comment by Fortigate** [comment]
With v33 right? This should have been fixed in 96de9ac646c1256818c7bea5477613ee99bf5989 , so that both Raids and Trials upon closing due to lack of resources turn off autoShrine settings.

**Comment by Larrush** [comment]
Oh my bad!
I'll get the latest master and compile it.
Thanks for the answer 😁
