### ISSUE TITLE
 ignore breaks

### ISSUE THREAD

**Issue by zenblob** [Betalord/BHBot#34]
the system ignores the pause command.
![pause](https://user-images.githubusercontent.com/48311971/54324278-641a5300-45fd-11e9-8b58-1736a413ee64.PNG)

**Comment by Fortigate** [comment]
Pause often does not instantly pause the bot, but after the current task (nearly always less than 10 seconds) it returns the bot to an idle state.

@ilpersi made some changes to the pause code recently, he can probably advise better if it's an issue related to that.

**Comment by ilpersi** [comment]
Nope: I only added the possibility to specify how many minutes do you want to pause the bot (it happened to me that I forgot to resume it). If you don't specify any value, the behavior is exactly the same as before as the scheduler logic is unchanged.

@zenblob is this happening randomly or is it happening systematically? Are you using he V33 or a self compiled version from the src?

**Comment by zenblob** [comment]
I'm using the compiled version. 
regarding the source version, I'm trying to figure out how to do it

**Comment by ilpersi** [comment]
Ok, is this happening randomly or every time you pause?

**Comment by zenblob** [comment]
randomly, sometimes it works well

**Comment by ilpersi** [comment]
It may randomly happen based on what the bot is doing and it is normal. Do you have an idea of the frequency? BTW if you are not AFK this should not be a major issue and the bot will resume anyway after 30 minutes.

**Comment by ilpersi** [comment]
I am going to close this one as I haven't been able to reproduce it and I did not get any feedback in a week.
The bot will survive this as it will automatically restart after 30 mins of inactivity.
