### ISSUE TITLE
Invalid World Boss Name

### ISSUE THREAD

**Issue by ToxicBarrel** [Betalord/BHBot#35]
Fresh folder, not sure if it's something on my end.

![cmd](https://user-images.githubusercontent.com/48550420/54346865-0e48a980-4603-11e9-8128-6981432aa27e.png)
![Code](https://user-images.githubusercontent.com/48550420/54346868-10126d00-4603-11e9-9f85-42199dbad355.png)

**Comment by Fortigate** [comment]
Strange, I have the same settings with no issue, can you check that there is no space after 'Melvin' and that you are running v33?  If that doesn't fix it I'll make a test build later to find the cause.

**Comment by ToxicBarrel** [comment]
I wasn't on v33. How could that of slipped my mind! Thanks for the support!
