### ISSUE TITLE
Something went wrong with driver restart

### ISSUE THREAD

**Issue by vincbou2013** [Betalord/BHBot#36]
When i launch bhbot.bat and chromedriver.exe, this message appear :  Something went wrong with driver restart. Will retry in a few minutes... (sleeping)

**Comment by ilpersi** [comment]
Make sure to follow all the steps in the [Detailed setup guide](https://github.com/Betalord/BHBot/wiki). In particular be sure to start chromedriver before running bhbot.bat.

**Comment by vincbou2013** [comment]
I've tried several times, don't seem to work. Might be doing something wrong if someone could do a quick screen record of the first setup it would be great.

**Comment by Larrush** [comment]
Did you start chromedriver as admin?

**Comment by vincbou2013** [comment]
no i havent let me try

**Comment by vincbou2013** [comment]
Nothing new, still not working. Dont know if it can help but when the message appear, on top of it, it is written : ( caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source) blablabla

**Comment by Larrush** [comment]
Do you have the .jar in the bhbot folder?

**Comment by vincbou2013** [comment]
nope

**Comment by vincbou2013** [comment]
you talking about the compiled bhbot.jar

**Comment by vincbou2013** [comment]
I did but this kind of message keep reappearing in the cmd : javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(Unknown Source)
        at MainThread.loadImage(MainThread.java:310)
        at MainThread.loadCues(MainThread.java:322)
        at BHBot.main(BHBot.java:36)

**Comment by Larrush** [comment]
To make it easier, just put all necessary files into the bhbot folder.
I even put the chromedriver in there.
Get the latest flash from the website thats in the first setup page and try again to initiate it.
I am not sure bit this seems to be a flash issue

**Comment by vincbou2013** [comment]
Still not working, i have placed every single file in the bhbot :/

**Comment by ilpersi** [comment]
You folder structure has to be like the picture below and you are sure that Chromium is closed.

After this
* you start chromedriver
* you run bhbot.bat

![image](https://user-images.githubusercontent.com/43588107/54488358-2c333a00-48a1-11e9-9885-04ef30125391.png)

**Comment by vincbou2013** [comment]
I did everything, i have created a new folder, reinstalled every single thing but there is 2 folders that I dont have! : Target, BHBot.iml.

And is it a problem if the logo og my BHBOT.jar is winrar not java?

**Comment by Larrush** [comment]
What do you mean when in the WinRar? 
Did you unpack the downloaded  .zip file?

Please take a screenshot of your folder and upload it here.

**Comment by vincbou2013** [comment]
![Screenshot - 2019-03-17 , 11_25_46](https://user-images.githubusercontent.com/48608619/54493530-8afbb200-48a7-11e9-8eca-9e34c45cae18.png)

**Comment by Larrush** [comment]
It seems you are missing the bhbot.jar.

Without this .jar chromedriver doesn´t know what to do with with the .bat file.

You don´t need the packed file in the BhBot folder itself. https://github.com/Betalord/BHBot/releases/download/v33/BHBot.jar

That´s what seems to be missing.
After you have the necessary files go from start to finish through this guide
https://github.com/Betalord/BHBot/wiki

**Comment by vincbou2013** [comment]
ok so i can remove the packed file but i dont know where to get bhbot.jar , .bat and .iml

**Comment by vincbou2013** [comment]
and when i download : https://github.com/Betalord/BHBot/releases/download/v33/BHBot.jar
it appears like that
![Screenshot - 2019-03-17 , 12_20_09](https://user-images.githubusercontent.com/48608619/54494304-10cf2b80-48af-11e9-8b33-242ce2b7a8a5.png)

**Comment by Larrush** [comment]
Hmm, this can mean two things.

Either you don´t have this installed:
https://get.adobe.com/flashplayer/ 

Or at some point you changed the default app for this file which shouldn´t interfere with the .bat
What happens now if you try to go through the setup ?

**Comment by Larrush** [comment]
But I am pretty sure you are missing on of the apps
I guess you are missing the java app, which is the second one I posted.

Download the proper one for your system, and try again

**Comment by Larrush** [comment]
> ok so i can remove the packed file but i dont know where to get bhbot.jar , .bat and .iml

You already have the bhbot.bat and init.bat 
For you it says only 
"BhBot" and "init"
This just means you don´t have the option for extensions of file names on.
It´s not a problem, both of them are batch files which you can see in the type section of your folder

**Comment by vincbou2013** [comment]
OKIIIIIIII I GOT ITTTTT, after playing with the folders for more than an hour i understood that my problem was that the bot is looking for chromium but my chromium wasnt at the good place but know it is all good

**Comment by vincbou2013** [comment]
Last problem, when the game started, the bot stopped and said that : <2019/03/17 13:10:24> BHBot v33 started.
<2019/03/17 13:10:24> Idle mode started, no actions will be taken
<2019/03/17 13:10:24> Driver started succesfully
<2019/03/17 13:10:38> Game element found. Starting to run bot..
<2019/03/17 13:11:03> Disconnect has been detected. Probably due to user interaction. Sleeping for 1h...
<2019/03/17 13:11:03> Paused for 1h.

**Comment by vincbou2013** [comment]
dont worry now its working fine just need to change settings which is kind of hard

**Comment by Larrush** [comment]
The disconnect was probably not due to the bot.
Just try again

**Comment by vincbou2013** [comment]
its all good ty :D

**Comment by Larrush** [comment]
Ah perfect.
I know the first time setting up takes some time but its worth it 😉

**Comment by Larrush** [comment]
If everything works fine please close the issue so the developers know its solved
