### ISSUE TITLE
DPI scaling

### ISSUE THREAD

**Issue by PoloDePoli** [Betalord/BHBot#4]
Hi - the script fails when DPI is not 100%.
Running it on windows with 150% dpi scaling and it does not capture the full screen (as seen via shot command) - changed to 100% dpi scaling and everything (so far) seems to work.
Thanks.

**Comment by Fortigate** [comment]
Added a line to the Readme about this issue, seems the image recognition engine has issues with high resolution/non-standard DPI that I can't pin down, so will need to use workarounds.
