### ISSUE TITLE
Can't make Pushover Work

### ISSUE THREAD

**Issue by bbicudo** [Betalord/BHBot#41]
It's nothing super important but i configured Pushover and it doesn't send me any message :3

Any ideas?

**Comment by ilpersi** [comment]
There is an undocumented command to test the Pushover integration. It is `pomessage`. It works like other commands (stop, pause, reload) and you can specify a message after it like

    pomessage Testing PO integration

Do you get any feedback from that?

**Comment by ilpersi** [comment]
@bbicudo FYI: the `pomessage` command is now publicly documented. As I get more time I will also add more details to the documentation that in this moment is a bit poor. Please let me know if you still have issues.

**Comment by bbicudo** [comment]
Sorry for the delay @ilpersi. Had a problem with my equipment.

Tried to use pomessage but got no results. Nothing is actually sent to me as you can see in my pushover project page:

![Capturar](https://user-images.githubusercontent.com/22198380/54880655-c6f1c280-4e25-11e9-84dd-93d251e1f0c6.PNG)

**Comment by ilpersi** [comment]
Checkout the new v34.1 and the improved [Pushover documentation](https://github.com/Betalord/BHBot/wiki/Pushover-integration-Documentation#how-do-i-check-if-the-configuration-is-correct). Now it should be easier to set up the integration.

**Comment by bbicudo** [comment]
PERFECT! It's working 100% now.

Just 1 more doubt. Expedition (inferno) is sometimes hanging saying that "couldn't find difficulty" and skipping it.

Is it a bug? Should i open another thread to talk about it? (i'm worried that i'm bringing up too many issues at once :3 sorry).

Thanks!

**Comment by ilpersi** [comment]
Yes please open a new thread, I am closing this one as you got it working now. :)
