### ISSUE TITLE
expeditions, maybe bug on detecting resources

### ISSUE THREAD

**Issue by zenblob** [Betalord/BHBot#42]
My bot hangs at the Expedition screen
![err01 0](https://user-images.githubusercontent.com/48311971/54861064-84e05800-4d23-11e9-98cf-5bb3df4aa8ca.PNG)
![err01 1](https://user-images.githubusercontent.com/48311971/54861067-8742b200-4d23-11e9-8fb2-94d15bf8bdd0.PNG)

**Comment by eschwim** [comment]
This is due to the code in master not currently having the correct portal coordinates for the Inferno Dimension.  I have a PR (#43) in to fix this.

**Comment by ilpersi** [comment]
Ooops I did not noticed the PR and developed a different fix myself at the very same time. :)

Despite this I see this is still happening and I am not able to debug it as it happened while I was AFK.

**Comment by ilpersi** [comment]
I've added some failsafe checks in commint f8e50631d4bba5fb566fb05ca3bcdaef2358e517, let me know if this fixes the issue.

**Comment by ilpersi** [comment]
Failsafe helped, but it was not enough. Commit 4558c3aec553fbcd23e93a49682103cc8ffd33aa should finally fix this issue. :)

**Comment by zenblob** [comment]
I tried, but I don't have the skills to compile it myself, can I hope for a new release?

**Comment by ilpersi** [comment]
[v34](https://github.com/Betalord/BHBot/releases/tag/v34) is out, check it out!

**Comment by zenblob** [comment]
Many thanks
