### ISSUE TITLE
Chromedriver opens a new window

### ISSUE THREAD

**Issue by blandstreetbloom** [Betalord/BHBot#44]
Hi, 

Chromedriver opens up a new window but doesn't do anything with it (leaves it open). 
Getting this error: 

[10672:8760:0323/212127.267:ERROR:cache_util_win.cc(19)] Unable to move the cache: 5
[10672:8760:0323/212127.283:ERROR:cache_util.cc(140)] Unable to move cache folder C:\Users\bland-\Desktop\BHBot-master\chrome_profile\ShaderCache\GPUCache to C:\Users\bland-\Desktop\BHBot-master\chrome_profile\ShaderCache\old_GPUCache_000
[10672:8760:0323/212127.285:ERROR:disk_cache.cc(168)] Unable to create cache
[10672:8760:0323/212127.285:ERROR:shader_disk_cache.cc(620)] Shader Cache Creation failed: -2
Created new window in existing browser session.

Any thoughts? 
Just stating that I'm a total noob as with programming.

**Comment by Larrush** [comment]
Did you open chromedriver before that?
Was the bot already working before?
Was chromedriver opened as Admin?

**Comment by MWEckert** [comment]
I'm getting the same issue.  Just got everything up and running.  I haven't seen what triggers this from the game, but if I leave it, I'll have several extra windows open on the home page.  It doesn't seem to interfere with the bot.

**Comment by blandstreetbloom** [comment]
> Did you open chromedriver before that?
> Was the bot already working before?
> Was chromedriver opened as Admin?

* Yes, this just started happening. 
* Yes, worked without problems before. 
* No, did not open as admin. Will try that here on after. 
The issue started when the bot had been running for some hours. 

I googled a bit and found a somewhat similar problem which made me delete \GPUCache. This did not solve the problem. 
I restarted my computer and lo and behold - the problem is gone! (...For now) 
Will update if the error comes back.

**Comment by ilpersi** [comment]
This may sometime happen due to the bot crashing without saving browser information correctly.

The best way to solve this is to delete the `chrome_profile` folder in your BHBot folder and re-configure the bot from scratch as explained [here](https://github.com/Betalord/BHBot/wiki).
