### ISSUE TITLE
timeLastBadgesCheck shared between exped & GVG

### ISSUE THREAD

**Issue by eschwim** [Betalord/BHBot#49]
If you have both `doExpedition` and `doGVG` enabled in your settings, and GvG is active but expedition is not, GvG will never trigger due to the fact that they both rely on the `timeLastBadgesCheck` variable for timing.  Expedition status is evaluated first, and even though the expedition button is not found, it sets the timeLastBadgesCheck variable to the current time:
https://github.com/Betalord/BHBot/blob/277169c534105f404dacbf9d69f081b8d5adffbf/src/main/java/MainThread.java#L1434

This has the undesirable side of effect of GvG (which is checked later in the timing loop) never meeting its timing requirement, and thus never getting executed:
https://github.com/Betalord/BHBot/blob/277169c534105f404dacbf9d69f081b8d5adffbf/src/main/java/MainThread.java#L1976 

This is likely to have happened to some people this week, since we just transitioned from the Inferno expedition to GvG.  The short term fix for this is for users to set  `doExpedition 0` in their config files.  Longer term fixes might include either using different timing variables for the two code blocks, or moving expedition into the existing GvG/Invasion codeblock.

**Comment by Fortigate** [comment]
I was just looking into why this was happening, thanks for the short term fix / explanation.

**Comment by ilpersi** [comment]
Probably moving the expedition into the exixting GVG/Invasion codeblock is the best and cleanest solution.

**Comment by ilpersi** [comment]
I've moved everything badge related in the same codeblock. I'll test GVGV for the next couple of days to make sure that everything is fine. Won't be able to test Expedition till it is out again. :)

**Comment by ilpersi** [comment]
I had the bot running two days with no issues on GVG, so I would say that 1199267a891e55ce4710d7433e924ef9542910e6 fixes the issue. We'll see if there is a regression on expedition next time it is available. :)
