### ISSUE TITLE
ReconnectTimer 

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#51]
Hello again, 

I can´t change the reconnect timer anymore to a lower amount.

Even though I set it to 15 he still waits 1h

```
<2019/04/11 22:03:46> Game element found. Starting to run bot..
<2019/04/11 22:04:29> Disconnect has been detected. Probably due to user interaction. Sleeping for 1h...
<2019/04/11 22:04:29> Paused for 1h.
```

I lately get random disconnects and I would like to let him log back quicker ^^ 

Thanks already!

**Comment by ilpersi** [comment]
Can you please add the following line to your settings.ini?

`pauseOnDisconnect 15`

This should do the trick.

**Comment by ilpersi** [comment]
ERRATA: the current implementation is expecting paudeOnDisconnect in milliseconds and not in minutes, so the correct value is 15 * 1000 * 60 = 900000 and the correct line is

`pauseOnDisconnect 900000`

This is not how it should be, so I am going to fix it.

**Comment by Larrush** [comment]
Ok I will put the line into settings.ini to make him log back quicker.

Thabks again for the help!

**Comment by ilpersi** [comment]
Turned out I was totally mistaken and there was a bit of inconsistency in the code.

Starting from next version `pauseOnDisconnect` is now deprecated and you must use `reconnectTimer` instead.
