### ISSUE TITLE
Bot cannot exit D4 when not enough energy is present

### ISSUE THREAD

**Issue by Fortigate** [Betalord/BHBot#53]
If the 4th dungeon is started and the 'not enough energy' failsafe from processDungeon is triggered the bot cannot close the dialogue and return to the main screen as it's expecting the exit screens from D1-3.

**Comment by ilpersi** [comment]
I actually never tested the "not enough energy" part as I have a `minEnergyPercentage` high enough to never trigger it.

This to say that the issue may also happen with d1-3.

**Comment by Fortigate** [comment]
Yeah same, I was levelling a low level friends account and it triggered with `minEnergyPercentage 10` leaving under 20 energy, seems the route to close the window from D4 is different from D1-3 as they didn't have issues. I'll try and recreate and fix it.

**Comment by Fortigate** [comment]
Should be fixed as of https://github.com/Betalord/BHBot/commit/e8594bd1b69151acba774c64127ed1baceecab5e
