### ISSUE TITLE
dungeons when energy is low

### ISSUE THREAD

**Issue by irissian** [Betalord/BHBot#56]
it seems that the bot sometimes stays at the "not enough energy" popup, and the console shows that the dungeon was initiated, and nothing changes

**Comment by ilpersi** [comment]
This is probably the same as #53 .

Currently the workaround is to increate `minEnergyPercentage` setting in settings.ini so that your energy never goes below 30.

**Comment by Fortigate** [comment]
Will look into this later

**Comment by Fortigate** [comment]
Was likely the `activityDuration` setting on energy check I added, after 10 seconds it would stop looking for the 'Not enough energy' popup. Changed it to 30 seconds in https://github.com/Betalord/BHBot/commit/e8594bd1b69151acba774c64127ed1baceecab5e
