### ISSUE TITLE
dungeon's marchant

### ISSUE THREAD

**Issue by irissian** [Betalord/BHBot#57]
bot seems to do nothing when encounting the marchant

**Comment by Fortigate** [comment]
Do you mean the bot opens the merchant dialogue and gets stuck? As far as I remember the bot doesn't support declining/accept merchant offers, you need to set 'auto-decline merchant' using the in game settings.

**Comment by ilpersi** [comment]
Fortigate is right: you need to disable merchants using the in game settings. Even tough maybe some kind of improvements can be useful here.

**Comment by Fortigate** [comment]
I propose we add to the initial setup that disabling merchant is a necessary step, past zone 1-2 there's no value in it, and adding a cue detection to the processDungeon function increases overhead with no real gain.

**Comment by ilpersi** [comment]
IMHO opinion adding a check during the dungeon is easier than going through the setting dialog and managing the interaction with the other features (e.g. Auto Shrine).

In the end what you are looking for is stability and if finishing a dungeon is a couple of second slower is not such a big issue.

The code [was already there](https://github.com/Betalord/BHBot/commit/da6d14fdcc62070efd12bff26f19f19faf91f7a0#diff-b872c1394db83d44effaa3ab684e3ef0L3600), it is few lines and we just need to restore it. This is much easier and faster than developing and test something new. :)

**Comment by Fortigate** [comment]
Ah, I meant the wiki guide for first time set up of the bot, once it's set there it's saved and doesn't need to be touched again. I'm not sure about other users but I've had merchants disabled since about level 30.
