### ISSUE TITLE
familliars persuading/bribing

### ISSUE THREAD

**Issue by irissian** [Betalord/BHBot#58]
i want to know id there is a way to bribe/persuade only a specific familliar not by his rarity but by name

**Comment by ilpersi** [comment]
You can do this for bribe (see the familiars setting in settings.ini) and not for persuasion. At the moment persuasion is only by type.

**Comment by ilpersi** [comment]
Here is an extract of the settings.ini documentation.

```
# To get the list of all currently available familiars use the 'print familiars' command while the bot is running

# format is; squib 5; astaroth 1; violace 2. familiar name first, amount you want to bribe second
# When a familiar is bribed this file will be automatically updated with the updated bribe counter
familiars squib 0
```

**Comment by ilpersi** [comment]
I am closing this, if more help is needed please feel free to open a new one.
