### ISSUE TITLE
Better log management

### ISSUE THREAD

**Issue by ilpersi** [Betalord/BHBot#61]
Right now BHBot is only able to log to the standard input so it is up to the user to redirect the output to some kind of file if they want to keep them to analyze them later (maybe review how many raids have been done or see if errors were present).

As a user I would like logs to be saved in a dedicated folder and deleted after a certain amount of time to avoid having a cluttered hard-disk.

As a developer I would like to have different log levels, so for example while I am developing I can also output debug information that is useless once that the bot is released to the public.

**Comment by Fortigate** [comment]
This sounds really good, a last 7 days worth of logs would be helpful to see at a glance if raid team/t+g/pvp teams need to be reconfigured without opening the bot.

**Comment by Fortigate** [comment]
To add to this some readability functionality to the output would be useful, it's getting difficult to read the information at a glance, I was thinking that we indent all actions that occur inside an event (Reviving/Shrining/Bribing etc) should help.

**Comment by ilpersi** [comment]
My plan is to integrate [log4j](https://logging.apache.org/log4j/2.x/). With Mave it is just one new depencendy and after that some code refactory is required.

Easter holidays are coming, I may find some time to work on this.

**Comment by ilpersi** [comment]
I've pushed a first EXPERIMENTAL version of the log4j integration to master. I had it running fine for about 12 hours, I'll keep on testing.

**Comment by ilpersi** [comment]
master branch has fully working log4j integration, so I am closing this.
