### ISSUE TITLE
ReconectTimer

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#62]
The reconnect timer waits an hour, when set to 15.
`reconnectTimer 15`

**Comment by ilpersi** [comment]
What version of the bot are you using? Please make sure to update to [v36](https://github.com/Betalord/BHBot/releases/tag/v36).

**Comment by Larrush** [comment]
I should have the newest master from 16. April but I'll download the v36 and try it again to see if It helps

**Comment by Larrush** [comment]
Yep, downloading the new version and updating it with the newest master did the trick :) 

Thanks for the help! 
I always thought I know my way around computers and then this stuff happens xD
