### ISSUE TITLE
PvP Battle opponent selection

### ISSUE THREAD

**Issue by Fortigate** [Betalord/BHBot#64]
The PvP battle selection is untouched since they removed the 2200TS point cap, now if you have good familiars/gear it is more favourable to be able to select other opponents than the first slot which gives the lowest reward.

**Comment by ilpersi** [comment]
So how would you like to change the current logic?

**Comment by Fortigate** [comment]
I'm thinking an opponent cap based on tickets used (More tickets = less opponents), then a function to load the cue with the right bounds. Will check it out later.
