### ISSUE TITLE
Auto-gauntlet/trial/expedition difficulty adjustment

### ISSUE THREAD

**Issue by eschwim** [Betalord/BHBot#65]
Since player TSP changes over time (which changes the max level of gauntlet/trial/expedition that you can reliably complete), it would be nice if the bot was success/failure aware for specific badge event difficulty, and could automatically adjust up/downwards to determine the highest difficulty where it could reliably win.

**Comment by Fortigate** [comment]
Not sure on the viability of this, typically events drop Legendary+ loot on the boss/last wave so you would be trading the chance to get decent drops for a small amount of points (90%+ of points are gained without defeating the boss).

**Comment by ilpersi** [comment]
The value I see in this feature is when you loose too many fight in a row and the bot automatically decrease the difficulty.
