### ISSUE TITLE
autoShrine not re-enabled after failed raid

### ISSUE THREAD

**Issue by Fortigate** [Betalord/BHBot#67]
I've looked through the logic and can't find anything wrong, perhaps related to `shrinesChecked`. If I am defeated in a raid the bot disables autoShrine, then checks shards again and starts the raid without re-enabling autoShrine.

**Comment by ilpersi** [comment]
I should have fix this in afc559dcfbdfafc1ff2aa70418a9b8562c7f1ac2. Did you try that?

**Comment by Fortigate** [comment]
I was on the commit before, will update and re-open if necessary 👍
