### ISSUE TITLE
Saturday bonus resource charger

### ISSUE THREAD

**Issue by JustifySC** [Betalord/BHBot#71]
Typically there's not much point in running your resources on a friday other than pvp tickets. So, have a feature which allows the bot to run your resources until a certain time, after which your regen will 'charge' all the way and be full at the friday/saturday transition time. After which, the character will have full resources for saturday where the bonus is more useful.

**Comment by ilpersi** [comment]
You can already manage this using different configuration files.

What you have to do is create a subfolder named `plans` and populate it with different ini settings copied from settings.ini.

To switch between plans you only have to use the `plan` command while the bot is running. So for example if you have a plan named `friday.ini` the command you have to give to the console is:

`plan friday` (noticed that I omitted the .ini part)

Here is the basic layout:

![image](https://user-images.githubusercontent.com/43588107/57087639-ca1f7e80-6d00-11e9-9bd9-744a8940df53.png)

**Comment by ilpersi** [comment]
@JustifySC are you fine with the solution I proposed you?

**Comment by ilpersi** [comment]
I've got no feedback in one week, so I am closing this.
