### ISSUE TITLE
Auto Revive not available for invasion?

### ISSUE THREAD

**Issue by EricSpeidel** [Betalord/BHBot#73]
**Describe the bug**
I've looked at the main classes and it appears that there is currently no auto revive option for invasion. Maybe that would be a nice addition for pushing levels.
**To Reproduce**
I tried adding an "i" setting, since that was ignored I looked at the mainthread, where only t g r e seem to be present.
**Expected behavior**
An additional "i" flag in settings.ini to enable it for invasion.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium
 - Version v39, compiled

Thanks once again for the incredible effort!

**Comment by Larrush** [comment]
You cannot revive on invasion.
So this feature is not possible

**Comment by EricSpeidel** [comment]
How could I miss this... Thanks for the heads up!

**Comment by Larrush** [comment]
No problem :)
