### ISSUE TITLE
Adding new log levels/colours

### ISSUE THREAD

**Issue by Fortigate** [Betalord/BHBot#75]
I've looked online but I'm not too familiar with log4j or how its set up. Is it a simple task to add new log tags/colours? 

Just for aesthetics it would be nice to have resource readouts and autoshrine/autorevive functions seperate from everything else that goes into the INFO level logs.

**Comment by ilpersi** [comment]
Right now colors are based on levels and managed using a [PatternLayout](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout).

STDOUT
https://github.com/Betalord/BHBot/blob/44d5a90e4d2a388c5ec8295ec4162f5fd883d78b/src/main/java/BHBotConfigurationFactory.java#L29

STDERR
https://github.com/Betalord/BHBot/blob/44d5a90e4d2a388c5ec8295ec4162f5fd883d78b/src/main/java/BHBotConfigurationFactory.java#L37

If I understand correctly you want to create a new level in between INFO and WARNING to manage resource readouts and auto functions. Am I correct?

This should be doable and I need to review the documentation: log4j implementation in BHBot is pretty unique to manage the possibility of changing settings at run time with no configuration file (I had to look at the source as no documentation is available).

**Comment by ilpersi** [comment]
Much more easier than I originally believed. You now have two new log levels: AUTOFUNCTION and READOUT and you can access them with dedicated methods logger.autofunction and logger.readout.

Have fun. 👍 😄

**Comment by Fortigate** [comment]
You're a star, spent about 2 hours reading through log4j documentation last week and couldn't decipher it. Will have a play with implementing these.
