### ISSUE TITLE
Bot tries (and fails to) decline epic fams

### ISSUE THREAD

**Issue by mutusfa** [Betalord/BHBot#86]
Bot, configured to persuade all fams, tries to decline an epic Rexie.

1. Use default fam settings; [mine](https://github.com/Betalord/BHBot/files/3274232/settings.txt)
2. Run bot
3. Wait for epic fam to offer to persuade it
4. Check logs that bot couldn't find a decline button

Expected behavior
Bot tries to persuade epic fam

Desktop:
 - OS: Windows 10
 - Browser: Chromium v69
 - Version v40, commit 3b65b231b78463d86c333a4813dc9a4986959903

Including full logs is a major PITA (I have to reformat them by hand); in these logs you should see that I'm trying to capture all fams (common/rare persuasion was attempted) and there was a fam that bot tried to decline (and failed). It was Rexie I accidentally managed to persuade before bot restarted chromedriver. I also noticed something similar in R1, trying to persuade Squib, but didn't manage to click anything or catch details at that time.

```
02:37:58,561 INFO - Attempting Heroic z4d1
02:38:10,663 INFO - Dungeon <z4d1> initiated!
02:39:14,890 AUTOBRIBE - Familiar encountered
02:39:28,636 AUTOBRIBE - COMMON persuasion attempted.
02:39:33,146 AUTOBRIBE - Familiar encountered
02:39:42,483 AUTOBRIBE - COMMON persuasion attempted.
02:40:08,892 AUTOBRIBE - Familiar encountered
02:40:18,452 AUTOBRIBE - COMMON persuasion attempted.
02:40:21,766 WARN - Problem: 'Victory' window (as found in e.g. gauntlets) has been detected, but no 'Close' button. Ignoring...
02:40:45,353 WARN - Problem: 'Victory' window (as found in e.g. gauntlets) has been detected, but no 'Close' button. Ignoring...
02:40:51,190 AUTOBRIBE - Familiar encountered
02:41:00,578 AUTOBRIBE - RARE persuasion attempted.
02:41:52,527 AUTOBRIBE - Familiar encountered
02:41:56,929 ERROR - Impossible to find the decline button, restarting...
02:41:56,934 WARN - Doing driver emergency restart...
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 15048
Only local connections are allowed. 
```

**Comment by Fortigate** [comment]
Looks like the bot is consistently failing to recognize all epic encounters and crashing? I've been running the same version for a while with no issues which is strange, does the bot leave any error screenshots from the crashes?

**Comment by ilpersi** [comment]
@mutusfa I have been running the bot for a week without this happening.

Can you please share any screenshot if available?

**Comment by Fortigate** [comment]
Closing this as I don't think we'll get a response, I've not had any issues with persuading epic fams on any of my accounts either.
