### ISSUE TITLE
Worldboss settings invalid

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#90]
With the new Worldboss format I keep getting this message: 

```
23:20:02,662 ERROR - Invalid world boss name, check settings file
23:20:02,663 WARN - Invalid world boss settings detected, World Boss will be skipped
```
My settings look like this.

```
# World Boss Settings
# Format is 'worldBoss n 3 9'
# o=orlag, n=nether, m=melvin, followed by tier, then difficulty
worldBoss m 1 10
# World Boss Timer (time to get a full lobby, on timeout return to main screen)
worldBossTimer 60
# If the lobby doesn't fill in time, run a dungeon instead? (0 = no, 1 = yes), useful for non peak hours
dungeonOnTimeout 1
# World Boss solo setting if you want to run low tier HC's solo
worldBossSolo 1
```

And also one thing in the description, the order of tier and difficulty are turned around
If followed by tier and then difficulty the line would need to look like 

`worldBoss m 10 1`

I tried both, but it didn´t work for me.

When I use the old settings it still works.
I should have the proper version for the new format:
```
23:52:27,200 INFO - BHBot v40.1 build on Sun Jun 16 23:51:55 CEST 2019 started.
23:52:27,244 INFO - GIT commit id: 49e8c5324e5ff03c70ef4e771735e89fc714e2a6  time: 2019-06-10T01:47:19+0200
```

**Comment by Fortigate** [comment]
Are you running an older version with a newer settings file? I see the world boss string update was introduced a few commits after the version you're on. I'll pass over it again before v41 to add full sanitization and error checking for the old system, and better error messages.

**Comment by Fortigate** [comment]
Closing for now, if its still an issue with the latest commit just re-open
